{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "axi-oss.secretName" . }}
  labels:
    {{- include "axi-oss.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.snowflakePassword }}
  snowflake-password: {{ .Values.secrets.snowflakePassword | quote }}
  {{- end }}
  {{- if .Values.secrets.snowflakePrivateKey }}
  snowflake-private-key: {{ .Values.secrets.snowflakePrivateKey | quote }}
  {{- end }}
  {{- if and (eq .Values.config.storage "postgres") (not .Values.postgresql.enabled) .Values.externalPostgresql.password }}
  db-password: {{ .Values.externalPostgresql.password | quote }}
  {{- end }}
{{- end }}
